/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ded7c6f3-b86c-48cd-a9a7-b049da520be3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_mlLC1TFbH",
    "aws_user_pools_web_client_id": "1l4uldrp16mvfkrpd292nn3dft",
    "oauth": {}
};


export default awsmobile;
